version: '3.5'

services:
  rdde:
    build: .
    ports:
      # Port for rails servers.
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      # Ports for Rubymine (not sure if needed)
      - "1234:1234"
      - "26166:26168"
    volumes:
      - "../.:/rdde"
      - "gem_data:/usr/local/bundle"
    container_name: rdde
    command: "tail -f /dev/null"

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  redis:
    image: redis:4.0
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.7.6-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  vault:
    image: vault:1.0.1
    ports:
      - "8200:8200"
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_DEV_ROOT_TOKEN_ID: changeme
      VAULT_ADDR: http://vault:8200

volumes:
  mysql_data:
  rabbitmq_data:
  redis_data:
  gem_data:
